//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    public partial class CHITIETSP
    {
        //public CHITIETSP()
        //{
        //    //if (HINHANH1.Equals("~/img/imgProduct/") || HINHANH1.Equals(""))
        //    //    HINHANH1 = "~/img/imgProduct/";
        //    //else
        //    //    HINHANH1 = HINHANH1;
        //    //if (HINHANH2 == "~/img/imgProduct/" || HINHANH2.Length == 0)
        //    //    HINHANH2 = "~/img/imgProduct/";
        //    //else
        //    //    HINHANH2 = HINHANH2;
        //    //if (HINHANH3 == "~/img/imgProduct/" || HINHANH3.Length == 0)
        //    //    HINHANH3 = "~/img/imgProduct/";
        //    //else
        //    //    HINHANH3 = HINHANH3;
        //    //if (HINHANH4 == "~/img/imgProduct/" || HINHANH4.Length == 0)
        //    //    HINHANH4 = "~/img/imgProduct/";
        //    //else
        //    //    HINHANH4 = HINHANH4;
        //    //if (HINHANH5 == "~/img/imgProduct/" || HINHANH5.Length == 0)
        //    //    HINHANH5 = "~/img/imgProduct/";
        //    //else
        //    //    HINHANH5 = HINHANH5;
        //}
        public string MASANPHAM { get; set; }
        public Nullable<int> SL_TONG { get; set; }
        public Nullable<int> SL_SIZE36 { get; set; }
        public Nullable<int> SL_SIZE37 { get; set; }
        public Nullable<int> SL_SIZE38 { get; set; }
        public Nullable<int> SL_SIZE39 { get; set; }
        public Nullable<int> SL_SIZE40 { get; set; }
        public Nullable<int> SL_SIZE41 { get; set; }
        public Nullable<int> SL_SIZE42 { get; set; }
        public Nullable<int> SL_SIZE43 { get; set; }
        public string MAUSAC1 { get; set; }
        public string MAUSAC2 { get; set; }
        public string MAUSAC3 { get; set; }
        public string MAUSAC4 { get; set; }
        public string MAUSAC5 { get; set; }
        public string MAUSAC6 { get; set; }
        public string MAUSAC7 { get; set; }
        public string MAUSAC8 { get; set; }
        public string MAUSAC9 { get; set; }
        public string MAUSAC10 { get; set; }
        public string HINHANH1 { get; set; }
        public string HINHANH2 { get; set; }
        public string HINHANH3 { get; set; }
        public string HINHANH4 { get; set; }
        public string HINHANH5 { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload2 { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload3 { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload4 { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload5 { get; set; }
    }
}
