//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETSP
    {
        public string MASANPHAM { get; set; }
        public Nullable<int> SL_TONG { get; set; }
        public Nullable<int> SL_SIZE36 { get; set; }
        public Nullable<int> SL_SIZE37 { get; set; }
        public Nullable<int> SL_SIZE38 { get; set; }
        public Nullable<int> SL_SIZE39 { get; set; }
        public Nullable<int> SL_SIZE40 { get; set; }
        public Nullable<int> SL_SIZE41 { get; set; }
        public Nullable<int> SL_SIZE42 { get; set; }
        public Nullable<int> SL_SIZE43 { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
