//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETSP
    {
        public string MASP { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string MAUSAC { get; set; }
        public Nullable<int> KICHCO { get; set; }
        public string MOTA { get; set; }
        public byte[] HINHANH { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
